AntiMethodWebSite/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AntiMethodWebSite.Data;
using AntiMethodWebSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.IO;
using Grpc.Core;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json;

namespace AntiMethodWebSite.Controllers
{
    public class PostController : Controller
    {
        private UserManager<AppUser> _userManager;
        private SignInManager<AppUser> _signManager;
        private RoleManager<IdentityRole> _roleManager;
        private IHttpContextAccessor _httpContextAccessor;
        private IWebHostEnvironment _appEnvironment;
        private readonly ApplicationDbContext _context;

        private int PageSize = 5;

        public PostController(ApplicationDbContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, RoleManager<IdentityRole> roleManager, IHttpContextAccessor httpContextAccessor, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _signManager = signInManager;
            _roleManager = roleManager;
            _httpContextAccessor = httpContextAccessor;
            _appEnvironment = appEnvironment;
        }

        // GET: Post
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var posts = await GetOrderedPosts().ToListAsync();
            ViewBag.PostType = "";
            ViewBag.Title = "Главная";
            ViewBag.PageSize = PageSize;
            ViewBag.PageNumber = pageNumber ?? 1;
            ViewBag.TotalPages = (int)Math.Ceiling(posts.Count() / (double)PageSize);
            return View(posts.Skip(PageSize * ((pageNumber ?? 1) - 1)).Take(PageSize));
        }

        public async Task<IActionResult> News(int? pageNumber)
        {
            var posts = await GetOrderedPosts().Where(post => post.PostType == PostType.News).ToListAsync();
            ViewBag.PostType = "0";
            ViewBag.Title = "Новости";
            ViewBag.PageSize = PageSize;
            ViewBag.PageNumber = pageNumber ?? 1;
            ViewBag.TotalPages = (int)Math.Ceiling(posts.Count() / (double)PageSize);
            return View("Index", posts.Skip(PageSize * ((pageNumber ?? 1) - 1)).Take(PageSize));
        }

        public async Task<IActionResult> Tactics(int? pageNumber)
        {
            var posts = await GetOrderedPosts().Where(post => post.PostType == PostType.Tactics).ToListAsync();
            ViewBag.PostType = "1";
            ViewBag.Title = "Тактики";
            ViewBag.PageSize = PageSize;
            ViewBag.PageNumber = pageNumber ?? 1;
            ViewBag.TotalPages = (int)Math.Ceiling(posts.Count() / (double)PageSize);
            return View("Index", posts.Skip(PageSize * ((pageNumber ?? 1) - 1)).Take(PageSize));
        }

        public async Task<IActionResult> Logs(int? pageNumber)
        {
            var posts = await GetOrderedPosts().Where(post => post.PostType == PostType.Logs).ToListAsync();
            ViewBag.PostType = "2";
            ViewBag.Title = "Логи";
            ViewBag.PageSize = PageSize;
            ViewBag.PageNumber = pageNumber ?? 1;
            ViewBag.TotalPages = (int)Math.Ceiling(posts.Count() / (double)PageSize);
            return View("Index", posts.Skip(PageSize * ((pageNumber ?? 1) - 1)).Take(PageSize));
        }

        public async Task<IActionResult> Other(int? pageNumber)
        {
            var posts = await GetOrderedPosts().Where(post => post.PostType == PostType.Etc).ToListAsync();
            ViewBag.PostType = "3";
            ViewBag.Title = "Прочее";
            ViewBag.PageSize = PageSize;
            ViewBag.PageNumber = pageNumber ?? 1;
            ViewBag.TotalPages = (int)Math.Ceiling(posts.Count() / (double)PageSize);
            return View("Index", posts.Skip(PageSize * ((pageNumber ?? 1) - 1)).Take(PageSize));
        }

        private IQueryable<Post> GetOrderedPosts()
        {
            return _context.Post.OrderByDescending(p => p.CreationDate);
        }

        // GET: Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            var comments = await _context.Comment.Where(c => c.Post.Id == id).ToListAsync();
            var model = new PostViewModel { Post = post, Comments = comments };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Comment(string content, int postId)
        {
            var comment = new Comment();
            var post = await _context.Post.FirstOrDefaultAsync(m => m.Id == postId);

            if (post == null)
                return NotFound();

            var user = await _userManager.GetUserAsync(HttpContext.User);
            comment.Content = content;
            comment.Post = post;
            comment.Author = user;
            comment.CreateDate = DateTime.Now;
            _context.Add(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = postId });
        }

        public async Task<IActionResult> DeleteComment(int? id, int postId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment.FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            _context.Comment.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = postId });
        }

        // GET: Post/Create
        [Authorize]
        public async Task<IActionResult> Create(string type, string value)
        {
            ViewBag.TypeValue = value ?? "";
            ViewBag.Type = type == "Главная" ? "Выберите тематику" : type;

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (!await _userManager.IsInRoleAsync(user, "Author"))
                return Forbid();

            return View();
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,Author,PostType,CreationDate")] Post post, IFormFile uploadedFile)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                post.Author = user;
                post.CreationDate = DateTime.Now;
                post.ImagePath = AddFile(uploadedFile);
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Post/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,PostType,CreationDate,ImagePath")] Post post, IFormFile uploadedFile)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    post.EditDate = DateTime.Now;
                    if (uploadedFile != null && uploadedFile.Length > 0)
                        post.ImagePath = AddFile(uploadedFile);
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Post/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Post.FindAsync(id);
            _context.Post.Remove(post);

AntiMethodWebSite/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AntiMethodWebSite.Data;
using AntiMethodWebSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
namespace AntiMethodWebSite.Controllers
{
    public class RatingController : Controller
    {
        private UserManager<AppUser> _userManager;
        private SignInManager<AppUser> _signManager;
        private RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;

        public RatingController(ApplicationDbContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _signManager = signInManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var model = new List<RatingViewModel>();
            foreach (var user in _userManager.Users.Where(u => u.Rank >= Rank.Raider).OrderByDescending(u => u.Points).ToList())
            {
                model.Add(new RatingViewModel { UserName = user.UserName, Points = user.Points, Rank = user.Rank });
            }
            return View(model);
        }
    }
}

AntiMethodWebSite/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/favicons/favicon-16x16.png">
<link rel="manifest" href="~/favicons/site.webmanifest">
<link rel="mask-icon" href="~/favicons/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

AntiMethodWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AntiMethod</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@

    @Html.Partial("_Favicons")

    <link rel="stylesheet" href="~/lib/fontawesome-free-5.15.1-web/css/all.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.min.css" />
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <script src="~/lib/summernote/lang/summernote-ru-RU.min.js"></script>
    <script type="text/javascript" src="https://wow.zamimg.com/widgets/newsfeed.js"></script>
    <script src="https://discord.com/api/guilds/755172580117315695/widget.json"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Post" asp-action="Index"><img src="~/logo.png" alt="AntiMethod" class="img-fluid" style="height:50px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="News">Новости</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="Tactics">Тактики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="Logs">Логи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Post" asp-action="Other">Прочее</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Rating" asp-action="Index">Рейтинг</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="https://www.tinkoff.ru/sl/9LsQeXSWF9e" target="_blank">Поддержать сервер</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="col-md-4" style="padding-top:81px">
                <div class="card my-4">
                    <h5 class="card-header">Важное!</h5>
                    <div class="card-body">
                        <a href="@Url.Action("Details", "Post", new { id = 4 })" class="text-light">Краткий экскурс по сайту</a>
                        <br />
                        <a href="https://www.tinkoff.ru/sl/9LsQeXSWF9e" class="text-light" target="_blank">Поддержать сервер рублем</a>
                    </div>
                    <div class="card-footer">
                        @*<a href="https://discord.gg/VhkbeT8XrU" target="_blank" class="fab fa-discord text-light"></a>*@
                    </div>
                </div>
                @*<div class="whnews">
                </div>*@
                <div>
                    <iframe src="https://discord.com/widget?id=755172580117315695&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AntiMethod
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $WowheadNewsFeed.fetch(function (contents) {
            $('.whnews').html(contents);
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>